// The site's identity, as structured data: who publishes easytax.vip, what the
// site is called, and where else that name can be corroborated.
//
// Why this exists, in numbers. Google Search Console, 7 days to 2026-09-16,
// sorted by position — the ten best-ranking queries the site has:
//
//     easy tax app                            pos  4.0
//     easy tax                                pos  5.5
//     easytax software                        pos  5.5
//     esytax                                  pos  8.0
//     easytax                                 pos  9.2
//     mtd timetable                           pos 17.9
//     office at home tax deduction            pos 21.0
//     working from home allowable expenses    pos 21.0
//
// Seven of the ten are people typing our own name, and the best of them is
// position 4. Somebody who already knows the product and searches for it gets
// three to eight other results first. That is the cheapest traffic there is
// and we are losing it before the query is even about tax.
//
// Part of the reason is that until now the site never said, in machine-readable
// form, that `EasyTax` is a name for anything. There was a SoftwareApplication
// node and per-page `publisher: { name: 'Finance Panda Limited' }` strings with
// no `@id`, so no Organization entity existed at all — nothing for the brand
// name to attach to, no `alternateName` covering the spellings people actually
// type, and no `sameAs` pointing anywhere a claim could be checked.
//
// Three nodes, one `@graph`, cross-referenced by `@id`:
//
//   #organization  Finance Panda Limited, the legal entity. Carries `sameAs`.
//   #website       easytax.vip. This is the node Google reads for the site
//                  name shown above the URL in a result.
//   #software      EasyTax the product. Already existed; now points its
//                  `publisher` at #organization instead of restating it.
//
// `sameAs` is the load-bearing part and it is deliberately empty today. It is
// for third-party profiles that describe the same entity — a Companies House
// record, a software directory listing — and an entry that 404s or describes
// somebody else is worse than no entry. Add each URL here only once the
// listing is live and names Finance Panda Limited or EasyTax.

export const SITE_URL = 'https://easytax.vip';

export const ORG_ID = `${SITE_URL}/#organization`;
export const WEBSITE_ID = `${SITE_URL}/#website`;
export const SOFTWARE_ID = `${SITE_URL}/#software`;

/**
 * Spellings of the brand that real people type. Taken from Search Console
 * rather than invented: `easy tax`, `easytax software`, `easy tax app` and the
 * typo `esytax` are all queries the site has been served for.
 *
 * `esytax` is included on purpose. It is a misspelling, not a name we use, but
 * `alternateName` is a statement about what the entity is called, and it is
 * plainly what that searcher meant.
 */
export const BRAND_ALTERNATE_NAMES = [
  'Easy Tax',
  'EasyTax Software',
  'EasyTax UK',
  'EasyTax app',
  'esytax',
];

/**
 * Third-party pages describing this same entity.
 *
 * EMPTY BY DESIGN — see the note at the top of this file. Append a URL only
 * when the listing is live and public, and check it names Finance Panda
 * Limited or EasyTax. A dead or mismatched `sameAs` is a worse signal than an
 * absent one, because it is a checkable claim that fails the check.
 */
export const SAME_AS: string[] = [];

/** 180×180 PNG, generated by app/apple-icon.tsx. Google's logo guidance wants
 *  a raster image of at least 112×112; the 32×32 `/icon` is below that. */
export const LOGO_URL = `${SITE_URL}/apple-icon`;

const organization = {
  '@type': 'Organization',
  '@id': ORG_ID,
  name: 'EasyTax',
  legalName: 'Finance Panda Limited',
  alternateName: BRAND_ALTERNATE_NAMES,
  url: SITE_URL,
  logo: { '@type': 'ImageObject', url: LOGO_URL, width: 180, height: 180 },
  // The one claim on /trust a stranger can independently verify, so it belongs
  // in the entity too: the ICO's public register is searchable by reference.
  identifier: {
    '@type': 'PropertyValue',
    name: 'ICO registration',
    value: 'ZA540758',
  },
  address: {
    '@type': 'PostalAddress',
    addressLocality: 'London',
    addressCountry: 'GB',
  },
  areaServed: { '@type': 'Country', name: 'United Kingdom' },
  ...(SAME_AS.length > 0 ? { sameAs: SAME_AS } : {}),
};

const website = {
  '@type': 'WebSite',
  '@id': WEBSITE_ID,
  name: 'EasyTax',
  alternateName: BRAND_ALTERNATE_NAMES,
  url: SITE_URL,
  inLanguage: 'en-GB',
  publisher: { '@id': ORG_ID },
};

const software = {
  '@type': 'SoftwareApplication',
  '@id': SOFTWARE_ID,
  name: 'EasyTax',
  alternateName: BRAND_ALTERNATE_NAMES,
  applicationCategory: 'FinanceApplication',
  operatingSystem: 'Web',
  url: SITE_URL,
  description:
    'UK tax software for freelancers and limited companies. File Self Assessment, VAT returns, CT600, Balance Sheet and P&L directly with HMRC for £24 per submission, no subscription.',
  // Was price '0' / "Free", which contradicted the £24 Offer on the homepage
  // and pricing page. Conflicting Offer nodes on the same URL are a rich-result
  // liability and read as a bait-and-switch to anyone who checks.
  offers: {
    '@type': 'Offer',
    price: '24',
    priceCurrency: 'GBP',
    description: '£20 + VAT (£24 inc. VAT) per HMRC submission — no subscription, no card to sign up',
  },
  featureList: [
    'Self Assessment (SA100)',
    'Making Tax Digital for Income Tax (MTD ITSA)',
    'Quarterly HMRC updates',
    'VAT returns (MTD VAT)',
    'CT600 Corporation Tax',
    'Balance Sheet',
    'Profit & Loss',
    'Open Banking integration',
    'AI expense categorisation',
  ],
  publisher: { '@id': ORG_ID },
  audience: {
    '@type': 'Audience',
    audienceType: 'UK freelancers, sole traders, contractors, and limited companies',
    geographicArea: { '@type': 'Country', name: 'United Kingdom' },
  },
};

/**
 * The site-wide entity graph, emitted once from `app/layout.tsx`.
 *
 * A single `@graph` rather than three sibling `<script>` tags: the nodes refer
 * to each other by `@id`, and one document keeps those references resolvable
 * without a consumer having to join across scripts.
 */
export const siteEntityGraph = {
  '@context': 'https://schema.org',
  '@graph': [organization, website, software],
};
